#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const printUsage = () => {
  console.log(
    [
      "Usage:",
      "  pnpm tweakcn:import --name <theme-name> --in <path|-> [--force]",
      "",
      "Options:",
      "  --name, -n   Theme name (used for file names and UI label)",
      "  --in, -i     Input CSS file path (use '-' to read from stdin)",
      "  --force, -f  Overwrite existing files",
    ].join("\n"),
  );
};

const args = process.argv.slice(2);
const options = {
  name: "",
  input: "",
  force: false,
};

for (let i = 0; i < args.length; i += 1) {
  const arg = args[i];
  if (arg === "--name" || arg === "-n") {
    options.name = args[i + 1] ?? "";
    i += 1;
    continue;
  }
  if (arg === "--in" || arg === "-i") {
    options.input = args[i + 1] ?? "";
    i += 1;
    continue;
  }
  if (arg === "--force" || arg === "-f") {
    options.force = true;
    continue;
  }
  if (arg === "--help" || arg === "-h") {
    printUsage();
    process.exit(0);
  }
}

const slugify = (value) => {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
};

const readStdin = async () => {
  if (process.stdin.isTTY) {
    return "";
  }
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString("utf8");
};

const extractBlock = (css, selectors) => {
  for (const selector of selectors) {
    const startIndex = css.indexOf(selector);
    if (startIndex === -1) {
      continue;
    }
    const braceStart = css.indexOf("{", startIndex + selector.length);
    if (braceStart === -1) {
      continue;
    }
    let depth = 0;
    for (let i = braceStart; i < css.length; i += 1) {
      const char = css[i];
      if (char === "{") {
        depth += 1;
        continue;
      }
      if (char === "}") {
        depth -= 1;
        if (depth === 0) {
          return css.slice(braceStart + 1, i);
        }
      }
    }
  }
  return null;
};

const formatRootBlock = (content) => {
  const lines = content
    .trim()
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  if (lines.length === 0) {
    return "";
  }
  return `:root {\n  ${lines.join("\n  ")}\n}\n`;
};

const writeFileSafe = async (filePath, content, force) => {
  try {
    await fs.access(filePath);
    if (!force) {
      throw new Error(`File already exists: ${filePath}`);
    }
  } catch (error) {
    if (error?.code !== "ENOENT" && !force) {
      throw error;
    }
  }
  await fs.writeFile(filePath, content, "utf8");
};

const run = async () => {
  if (!options.name) {
    console.error("Missing --name.");
    printUsage();
    process.exit(1);
  }

  const slug = slugify(options.name);
  if (!slug) {
    console.error("Theme name must contain letters or numbers.");
    process.exit(1);
  }

  let css = "";
  if (options.input && options.input !== "-") {
    css = await fs.readFile(path.resolve(process.cwd(), options.input), "utf8");
  } else {
    css = await readStdin();
  }

  if (!css.trim()) {
    console.error("No CSS input provided.");
    printUsage();
    process.exit(1);
  }

  const lightBlock = extractBlock(css, [":root"]);
  if (!lightBlock) {
    console.error("Could not find a :root { ... } block in the input.");
    process.exit(1);
  }

  const darkBlock = extractBlock(css, [".dark:root", ".dark", ":root.dark", "[data-theme=\"dark\"]"]);

  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const webRoot = path.resolve(scriptDir, "..");
  const outDir = path.join(webRoot, "src", "themes", "tweakcn");

  await fs.mkdir(outDir, { recursive: true });

  const header = "/* Generated by tweakcn-import. Edit as needed. */\n";
  const lightCss = header + formatRootBlock(lightBlock);
  const lightPath = path.join(outDir, `${slug}.css`);
  await writeFileSafe(lightPath, lightCss, options.force);

  if (darkBlock) {
    const darkCss = header + formatRootBlock(darkBlock);
    const darkPath = path.join(outDir, `${slug}-dark.css`);
    await writeFileSafe(darkPath, darkCss, options.force);
  }

  console.log(`Theme files written to ${outDir}`);
};

run().catch((error) => {
  console.error(error?.message ?? error);
  process.exit(1);
});
